---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# histomaker Package

<!-- badges: start -->
<!-- badges: end -->

The goal of histomaker is to easily plot a histogram using user-specified data and be able to 
change aethetics efficiently!

## Installation

Package installation can be done directly by calling
`devtools::install_github("kelsey-mcguire/histomaker")`

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(histomaker)
## basic example code

# EXAMPLES USE RANDOM DATASET (BELOW)
## create a random dataset that has an ID and value column where values are distributed normally
random_data <- data.frame(id = 1:132, values = rnorm(n=132, mean = 23, sd = 7))

# EXAMPLE 1: NO AESTHETICS APPLIED
## apply the histogram function, employing a bin width of 3 displaying the distribution of values
ex1 <- histo_function(random_data, values, 3)

# EXAMPLE 2: AESTHETICS APPLIED
## corrected histogram column name to get a returned plot showing the distribution of height ranges
ex2 <- histo_function(random_data, values, 5, fill_colour = "hotpink")
```


